pruebas_index:
    path: /pruebas/{lang}/{name}/{page}
    defaults: {_controller: AppBundle:Pruebas:index,lang: es,name:nombre_defecto, page:1}
    methods: [GET]
    requirements:
        #name: \w+
        mame: "[a-zA-Z]*"
        page: \d+
        lang: es|en|fr